[build]
  base = "project"       # Netlify will run commands in /project
  command = "npm run build"
  publish = "project/dist"  # Where your built files will be

[dev]
  command = "npm run dev"
  publish = "project"    # For local dev server