[build]
  command = "cd project && npm run build"  # Explicit directory change
  publish = "project/dist"  # Single project reference
  functions = "functions"

[dev]
  command = "cd project && npm run dev"
  port = 5173
  publish = "project"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true