[build]
  base = "project"   
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 5173
  publish = "project"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 