[build]
  base = "project"               # All commands run inside /project
  command = "npm install && npm run build"
  publish = "project/dist"       # Where Vite outputs files

[dev]
  command = "npm run dev"        # Runs from /project due to base
  port = 5173                    # Must match Vite's default
  publish = "project"            # Source files location

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true                   # Critical for SPAs