[build]
  command = "npm run build"
  publish = "dist"  # Vite's default output directory
  functions = "functions"  # Only if using Netlify Functions

[dev]
  command = "npm run dev"
  port = 5173  # Vite's default port
  targetPort = 5173
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true