[build]
  base = "project"       # Sets the working directory during build
  publish = "project/dist"  # Netlify should serve from project/dist
  command = "npm run build"

[dev]
  command = "npm run dev"
  port = 3000            # Should match your dev server port
  publish = "project"    # For Netlify Dev

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true